export const REACTIONS = [
  { id: "like", emoji: "👍", label: "Нравится" },
  { id: "love", emoji: "❤️", label: "Любовь" },
  { id: "laugh", emoji: "😂", label: "Смешно" },
  { id: "wow", emoji: "😮", label: "Вау" },
  { id: "sad", emoji: "😢", label: "Грустно" },
  { id: "angry", emoji: "😡", label: "Злость" },
  { id: "fire", emoji: "🔥", label: "Огонь" },
  { id: "clap", emoji: "👏", label: "Аплодисменты" },
  { id: "cry", emoji: "😭", label: "Плачу" },
  { id: "think", emoji: "🤔", label: "Думаю" },
  { id: "shock", emoji: "😱", label: "Шок" },
  { id: "100", emoji: "💯", label: "Сотка" },
  { id: "party", emoji: "🎉", label: "Праздник" },
  { id: "eyes", emoji: "👀", label: "Смотрю" },
  { id: "pray", emoji: "🙏", label: "Пожалуйста" },
  { id: "muscle", emoji: "💪", label: "Сила" },
  { id: "facepalm", emoji: "🤦", label: "Фейспалм" },
  { id: "dislike", emoji: "👎", label: "Не нравится" },
  { id: "ok", emoji: "👌", label: "Окей" },
  { id: "rocket", emoji: "🚀", label: "Ракета" },
] as const

export type EmojiId = (typeof REACTIONS)[number]["id"]
// 💦👏🤝🍾🧸🐻🌋🍌🍓🥒🍆🌽🥕🌭🍺🦍🦧🦥🦉🌪️🥰😍🤩🤑🤤😅🤧🤯😤💩☢️🏴‍☠️👑💎💨💄🗿🧬✍️💅🙌🧠🙈🙉🙊😲😱😢🤒🤮🤢🤥🤨😎😘😍🤣🌯🍸🎲🎰🏆🗽🗼🎠🏝🏜🦠🧻🃏

// const popularEmojis = [
//   { id: "like", emoji: "👍", label: "Нравится" },
//   { id: "love", emoji: "❤️", label: "Любовь" },
//   { id: "fire", emoji: "🔥", label: "Огонь" },
//   { id: "laugh", emoji: "😂", label: "Смех" },
//   { id: "smile", emoji: "😊", label: "Улыбка" },
//   { id: "heart_eyes", emoji: "😍", label: "В восторге" },
//   { id: "clap", emoji: "👏", label: "Аплодисменты" },
//   { id: "thinking", emoji: "🤔", label: "Задумчивость" },
//   { id: "cry", emoji: "😭", label: "Плач" },
//   { id: "surprise", emoji: "😮", label: "Удивление" },

//   { id: "cool", emoji: "😎", label: "Круто" },
//   { id: "wink", emoji: "😉", label: "Подмигивание" },
//   { id: "kiss", emoji: "😘", label: "Поцелуй" },
//   { id: "angry", emoji: "😡", label: "Злость" },
//   { id: "party", emoji: "🥳", label: "Праздник" },
//   { id: "star", emoji: "⭐", label: "Звезда" },
//   { id: "ok", emoji: "👌", label: "Ок" },
//   { id: "pray", emoji: "🙏", label: "Спасибо" },
//   { id: "muscle", emoji: "💪", label: "Сила" },
//   { id: "eyes", emoji: "👀", label: "Смотрю" },

//   { id: "rocket", emoji: "🚀", label: "Ракета" },
//   { id: "poop", emoji: "💩", label: "Какашка" },
//   { id: "skull", emoji: "💀", label: "Смерть от смеха" },
//   { id: "check", emoji: "✅", label: "Готово" },
//   { id: "cross", emoji: "❌", label: "Ошибка" },
//   { id: "warning", emoji: "⚠️", label: "Предупреждение" },
//   { id: "sparkles", emoji: "✨", label: "Блеск" },
//   { id: "wave", emoji: "👋", label: "Привет" },
//   { id: "handshake", emoji: "🤝", label: "Сделка" },
//   { id: "broken_heart", emoji: "💔", label: "Разбитое сердце" },

//   { id: "sun", emoji: "☀️", label: "Солнце" },
//   { id: "moon", emoji: "🌙", label: "Луна" },
//   { id: "cloud", emoji: "☁️", label: "Облако" },
//   { id: "rainbow", emoji: "🌈", label: "Радуга" },
//   { id: "snow", emoji: "❄️", label: "Снег" },
//   { id: "coffee", emoji: "☕", label: "Кофе" },
//   { id: "pizza", emoji: "🍕", label: "Пицца" },
//   { id: "burger", emoji: "🍔", label: "Бургер" },
//   { id: "cake", emoji: "🎂", label: "Торт" },
//   { id: "beer", emoji: "🍺", label: "Пиво" },

//   { id: "dog", emoji: "🐶", label: "Собака" },
//   { id: "cat", emoji: "🐱", label: "Кот" },
//   { id: "bear", emoji: "🐻", label: "Медведь" },
//   { id: "panda", emoji: "🐼", label: "Панда" },
//   { id: "lion", emoji: "🦁", label: "Лев" },
//   { id: "tiger", emoji: "🐯", label: "Тигр" },
//   { id: "monkey", emoji: "🐵", label: "Обезьяна" },
//   { id: "chicken", emoji: "🐔", label: "Курица" },
//   { id: "fish", emoji: "🐟", label: "Рыба" },
//   { id: "whale", emoji: "🐳", label: "Кит" },

//   { id: "car", emoji: "🚗", label: "Машина" },
//   { id: "bike", emoji: "🚲", label: "Велосипед" },
//   { id: "plane", emoji: "✈️", label: "Самолет" },
//   { id: "train", emoji: "🚆", label: "Поезд" },
//   { id: "ship", emoji: "🚢", label: "Корабль" },
//   { id: "phone", emoji: "📱", label: "Телефон" },
//   { id: "laptop", emoji: "💻", label: "Ноутбук" },
//   { id: "camera", emoji: "📷", label: "Камера" },
//   { id: "game", emoji: "🎮", label: "Игра" },
//   { id: "music", emoji: "🎵", label: "Музыка" },

//   { id: "gift", emoji: "🎁", label: "Подарок" },
//   { id: "balloon", emoji: "🎈", label: "Шарик" },
//   { id: "trophy", emoji: "🏆", label: "Трофей" },
//   { id: "medal", emoji: "🥇", label: "Медаль" },
//   { id: "soccer", emoji: "⚽", label: "Футбол" },
//   { id: "basketball", emoji: "🏀", label: "Баскетбол" },
//   { id: "tennis", emoji: "🎾", label: "Теннис" },
//   { id: "book", emoji: "📚", label: "Книги" },
//   { id: "pen", emoji: "🖊️", label: "Ручка" },
//   { id: "lock", emoji: "🔒", label: "Замок" },

//   { id: "key", emoji: "🔑", label: "Ключ" },
//   { id: "money", emoji: "💰", label: "Деньги" },
//   { id: "credit_card", emoji: "💳", label: "Карта" },
//   { id: "chart_up", emoji: "📈", label: "Рост" },
//   { id: "chart_down", emoji: "📉", label: "Падение" },
//   { id: "lightbulb", emoji: "💡", label: "Идея" },
//   { id: "mag", emoji: "🔍", label: "Поиск" },
//   { id: "bell", emoji: "🔔", label: "Уведомление" },
//   { id: "hourglass", emoji: "⏳", label: "Ожидание" },
//   { id: "hammer", emoji: "🔨", label: "Инструмент" },

//   { id: "shield", emoji: "🛡️", label: "Защита" },
//   { id: "crown", emoji: "👑", label: "Корона" },
//   { id: "ghost", emoji: "👻", label: "Призрак" },
//   { id: "alien", emoji: "👽", label: "Пришелец" },
//   { id: "robot", emoji: "🤖", label: "Робот" },
//   { id: "brain", emoji: "🧠", label: "Мозг" },
//   { id: "eyes_heart", emoji: "🥰", label: "Нежность" },
//   { id: "neutral", emoji: "😐", label: "Нейтрально" },
//   { id: "sleep", emoji: "😴", label: "Сон" },
//   { id: "explosion", emoji: "💥", label: "Взрыв" }
// ]

// const chatEmojis = [
//   { id: "like", emoji: "👍", label: "Нравится" },
//   { id: "dislike", emoji: "👎", label: "Не нравится" },
//   { id: "love", emoji: "❤️", label: "Любовь" },
//   { id: "laugh", emoji: "😂", label: "Смешно" },
//   { id: "cry_laugh", emoji: "🤣", label: "Угар" },
//   { id: "smile", emoji: "😊", label: "Улыбка" },
//   { id: "heart_eyes", emoji: "😍", label: "В восторге" },
//   { id: "fire", emoji: "🔥", label: "Огонь" },
//   { id: "clap", emoji: "👏", label: "Браво" },
//   { id: "wow", emoji: "😮", label: "Вау" },

//   { id: "think", emoji: "🤔", label: "Хм" },
//   { id: "facepalm", emoji: "🤦", label: "Фейспалм" },
//   { id: "shrug", emoji: "🤷", label: "Не знаю" },
//   { id: "ok", emoji: "👌", label: "Ок" },
//   { id: "pray", emoji: "🙏", label: "Спасибо" },
//   { id: "muscle", emoji: "💪", label: "Сила" },
//   { id: "eyes", emoji: "👀", label: "Смотрю" },
//   { id: "wave", emoji: "👋", label: "Привет" },
//   { id: "kiss", emoji: "😘", label: "Поцелуй" },
//   { id: "cool", emoji: "😎", label: "Круто" },

//   { id: "angry", emoji: "😡", label: "Злость" },
//   { id: "sad", emoji: "😢", label: "Грусть" },
//   { id: "shock", emoji: "😱", label: "Шок" },
//   { id: "sleep", emoji: "😴", label: "Сплю" },
//   { id: "party", emoji: "🥳", label: "Праздник" },
//   { id: "star", emoji: "⭐", label: "Звезда" },
//   { id: "rocket", emoji: "🚀", label: "Погнали" },
//   { id: "check", emoji: "✅", label: "Готово" },
//   { id: "cross", emoji: "❌", label: "Нет" },
//   { id: "question", emoji: "❓", label: "Вопрос" },

//   { id: "exclamation", emoji: "❗", label: "Важно" },
//   { id: "coffee", emoji: "☕", label: "Кофе?" },
//   { id: "beer", emoji: "🍺", label: "По пиву" },
//   { id: "pizza", emoji: "🍕", label: "Пицца?" },
//   { id: "gift", emoji: "🎁", label: "Подарок" },
//   { id: "trophy", emoji: "🏆", label: "Топ" },
//   { id: "ghost", emoji: "👻", label: "Бу" },
//   { id: "poop", emoji: "💩", label: "Фигня" },
//   { id: "skull", emoji: "💀", label: "Умер со смеху" },
//   { id: "sparkles", emoji: "✨", label: "Красиво" }
// ]
