const memsPath = "/stickers/mems/"
const MEMS = [
  { id: "mems-1", image: `${memsPath}mems-1.png` },
  { id: "mems-2", image: `${memsPath}mems-2.png` },
  { id: "mems-3", image: `${memsPath}mems-3.png` },
  { id: "mems-4", image: `${memsPath}mems-4.png` },
  { id: "mems-5", image: `${memsPath}mems-5.png` },
  { id: "mems-6", image: `${memsPath}mems-6.png` },
  { id: "mems-7", image: `${memsPath}mems-7.png` },
  { id: "mems-8", image: `${memsPath}mems-8.png` },
  { id: "mems-9", image: `${memsPath}mems-9.png` },
  { id: "mems-10", image: `${memsPath}mems-10.png` },
  { id: "mems-11", image: `${memsPath}mems-11.png` },
  { id: "mems-12", image: `${memsPath}mems-12.png` },
  { id: "mems-13", image: `${memsPath}mems-13.png` },
  { id: "mems-14", image: `${memsPath}mems-14.png` },
]

const capybaraPath = "/stickers/capybara/"
const CAPYBARA = [
  { id: "capybara-1", image: `${capybaraPath}capybara-1.png` },
  { id: "capybara-2", image: `${capybaraPath}capybara-2.png` },
  { id: "capybara-3", image: `${capybaraPath}capybara-3.png` },
  { id: "capybara-4", image: `${capybaraPath}capybara-4.png` },
  { id: "capybara-5", image: `${capybaraPath}capybara-5.png` },
  { id: "capybara-6", image: `${capybaraPath}capybara-6.png` },
  { id: "capybara-7", image: `${capybaraPath}capybara-7.png` },
  { id: "capybara-8", image: `${capybaraPath}capybara-8.png` },
  { id: "capybara-9", image: `${capybaraPath}capybara-9.png` },
  { id: "capybara-10", image: `${capybaraPath}capybara-10.png` },
  { id: "capybara-11", image: `${capybaraPath}capybara-11.png` },
  { id: "capybara-12", image: `${capybaraPath}capybara-12.png` },
  { id: "capybara-13", image: `${capybaraPath}capybara-13.png` },
  { id: "capybara-14", image: `${capybaraPath}capybara-14.png` },
  { id: "capybara-15", image: `${capybaraPath}capybara-15.png` },
  { id: "capybara-16", image: `${capybaraPath}capybara-16.png` },
  { id: "capybara-17", image: `${capybaraPath}capybara-17.png` },
  { id: "capybara-18", image: `${capybaraPath}capybara-18.png` },
  { id: "capybara-19", image: `${capybaraPath}capybara-19.png` },
  { id: "capybara-20", image: `${capybaraPath}capybara-20.png` },
  { id: "capybara-21", image: `${capybaraPath}capybara-21.png` },
  { id: "capybara-22", image: `${capybaraPath}capybara-22.png` },
]

const benderPath = "/stickers/bender/"
const BENDER = [
  { id: "bender-1", image: `${benderPath}bender-1.webp` },
  { id: "bender-2", image: `${benderPath}bender-2.webp` },
  { id: "bender-3", image: `${benderPath}bender-3.webp` },
  { id: "bender-4", image: `${benderPath}bender-4.webp` },
  { id: "bender-5", image: `${benderPath}bender-5.webp` },
  { id: "bender-6", image: `${benderPath}bender-6.webp` },
  { id: "bender-7", image: `${benderPath}bender-7.webp` },
  { id: "bender-8", image: `${benderPath}bender-8.webp` },
  { id: "bender-9", image: `${benderPath}bender-9.webp` },
  { id: "bender-10", image: `${benderPath}bender-10.webp` },
  { id: "bender-11", image: `${benderPath}bender-11.webp` },
  { id: "bender-12", image: `${benderPath}bender-12.webp` },
  { id: "bender-13", image: `${benderPath}bender-13.webp` },
  { id: "bender-14", image: `${benderPath}bender-14.webp` },
  { id: "bender-15", image: `${benderPath}bender-15.webp` },
  { id: "bender-16", image: `${benderPath}bender-16.webp` },
  { id: "bender-17", image: `${benderPath}bender-17.webp` },
  { id: "bender-18", image: `${benderPath}bender-18.webp` },
  { id: "bender-19", image: `${benderPath}bender-19.webp` },
  { id: "bender-20", image: `${benderPath}bender-20.webp` },
]

const cheshirePath = "/stickers/cheshire/"
const CHESHIRE = [
  { id: "cheshire-1", image: `${cheshirePath}cheshire-1.webp` },
  { id: "cheshire-2", image: `${cheshirePath}cheshire-2.webp` },
  { id: "cheshire-3", image: `${cheshirePath}cheshire-3.webp` },
  { id: "cheshire-4", image: `${cheshirePath}cheshire-4.webp` },
  { id: "cheshire-5", image: `${cheshirePath}cheshire-5.webp` },
  { id: "cheshire-6", image: `${cheshirePath}cheshire-6.webp` },
  { id: "cheshire-7", image: `${cheshirePath}cheshire-7.webp` },
  { id: "cheshire-8", image: `${cheshirePath}cheshire-8.webp` },
  { id: "cheshire-9", image: `${cheshirePath}cheshire-9.webp` },
  { id: "cheshire-10", image: `${cheshirePath}cheshire-10.webp` },
  { id: "cheshire-11", image: `${cheshirePath}cheshire-11.webp` },
  { id: "cheshire-12", image: `${cheshirePath}cheshire-12.webp` },
  { id: "cheshire-13", image: `${cheshirePath}cheshire-13.webp` },
  { id: "cheshire-14", image: `${cheshirePath}cheshire-14.webp` },
  { id: "cheshire-15", image: `${cheshirePath}cheshire-15.webp` },
  { id: "cheshire-16", image: `${cheshirePath}cheshire-16.webp` },
  { id: "cheshire-17", image: `${cheshirePath}cheshire-17.webp` },
  { id: "cheshire-18", image: `${cheshirePath}cheshire-18.webp` },
  { id: "cheshire-19", image: `${cheshirePath}cheshire-19.webp` },
  { id: "cheshire-20", image: `${cheshirePath}cheshire-20.webp` },
  { id: "cheshire-21", image: `${cheshirePath}cheshire-21.webp` },
  { id: "cheshire-22", image: `${cheshirePath}cheshire-22.webp` },
  { id: "cheshire-23", image: `${cheshirePath}cheshire-23.webp` },
  { id: "cheshire-24", image: `${cheshirePath}cheshire-24.webp` },
  { id: "cheshire-25", image: `${cheshirePath}cheshire-25.webp` },
  { id: "cheshire-26", image: `${cheshirePath}cheshire-26.webp` },
  { id: "cheshire-27", image: `${cheshirePath}cheshire-27.webp` },
  { id: "cheshire-28", image: `${cheshirePath}cheshire-28.webp` },
  { id: "cheshire-29", image: `${cheshirePath}cheshire-29.webp` },
  { id: "cheshire-30", image: `${cheshirePath}cheshire-30.webp` },
]

const cthulhuPath = "/stickers/cthulhu/"
const CTHULHU = [
  { id: "cthulhu-1", image: `${cthulhuPath}cthulhu-1.webp` },
  { id: "cthulhu-2", image: `${cthulhuPath}cthulhu-2.webp` },
  { id: "cthulhu-3", image: `${cthulhuPath}cthulhu-3.webp` },
  { id: "cthulhu-4", image: `${cthulhuPath}cthulhu-4.webp` },
  { id: "cthulhu-5", image: `${cthulhuPath}cthulhu-5.webp` },
  { id: "cthulhu-6", image: `${cthulhuPath}cthulhu-6.webp` },
  { id: "cthulhu-7", image: `${cthulhuPath}cthulhu-7.webp` },
  { id: "cthulhu-8", image: `${cthulhuPath}cthulhu-8.webp` },
  { id: "cthulhu-9", image: `${cthulhuPath}cthulhu-9.webp` },
  { id: "cthulhu-10", image: `${cthulhuPath}cthulhu-10.webp` },
  { id: "cthulhu-11", image: `${cthulhuPath}cthulhu-11.webp` },
  { id: "cthulhu-12", image: `${cthulhuPath}cthulhu-12.webp` },
  { id: "cthulhu-13", image: `${cthulhuPath}cthulhu-13.webp` },
  { id: "cthulhu-14", image: `${cthulhuPath}cthulhu-14.webp` },
  { id: "cthulhu-15", image: `${cthulhuPath}cthulhu-15.webp` },
  { id: "cthulhu-16", image: `${cthulhuPath}cthulhu-16.webp` },
  { id: "cthulhu-17", image: `${cthulhuPath}cthulhu-17.webp` },
  { id: "cthulhu-18", image: `${cthulhuPath}cthulhu-18.webp` },
  { id: "cthulhu-19", image: `${cthulhuPath}cthulhu-19.webp` },
  { id: "cthulhu-20", image: `${cthulhuPath}cthulhu-20.webp` },
]

const gucciPath = "/stickers/gucci/"
const GUCCI = [
  { id: "gucci-1", image: `${gucciPath}gucci-1.webp` },
  { id: "gucci-2", image: `${gucciPath}gucci-2.webp` },
  { id: "gucci-3", image: `${gucciPath}gucci-3.webp` },
  { id: "gucci-4", image: `${gucciPath}gucci-4.webp` },
  { id: "gucci-5", image: `${gucciPath}gucci-5.webp` },
  { id: "gucci-6", image: `${gucciPath}gucci-6.webp` },
  { id: "gucci-7", image: `${gucciPath}gucci-7.webp` },
  { id: "gucci-8", image: `${gucciPath}gucci-8.webp` },
  { id: "gucci-9", image: `${gucciPath}gucci-9.webp` },
  { id: "gucci-10", image: `${gucciPath}gucci-10.webp` },
  { id: "gucci-11", image: `${gucciPath}gucci-11.webp` },
  { id: "gucci-12", image: `${gucciPath}gucci-12.webp` },
  { id: "gucci-13", image: `${gucciPath}gucci-13.webp` },
  { id: "gucci-14", image: `${gucciPath}gucci-14.webp` },
  { id: "gucci-15", image: `${gucciPath}gucci-15.webp` },
  { id: "gucci-16", image: `${gucciPath}gucci-16.webp` },
]

const homerPath = "/stickers/homer/"
const HOMER = [
  { id: "homer-1", image: `${homerPath}homer-1.webp` },
  { id: "homer-2", image: `${homerPath}homer-2.webp` },
  { id: "homer-3", image: `${homerPath}homer-3.webp` },
  { id: "homer-4", image: `${homerPath}homer-4.webp` },
  { id: "homer-5", image: `${homerPath}homer-5.webp` },
  { id: "homer-6", image: `${homerPath}homer-6.webp` },
  { id: "homer-7", image: `${homerPath}homer-7.webp` },
  { id: "homer-8", image: `${homerPath}homer-8.webp` },
  { id: "homer-9", image: `${homerPath}homer-9.webp` },
  { id: "homer-10", image: `${homerPath}homer-10.webp` },
  { id: "homer-11", image: `${homerPath}homer-11.webp` },
  { id: "homer-12", image: `${homerPath}homer-12.webp` },
  { id: "homer-13", image: `${homerPath}homer-13.webp` },
  { id: "homer-14", image: `${homerPath}homer-14.webp` },
  { id: "homer-15", image: `${homerPath}homer-15.webp` },
  { id: "homer-16", image: `${homerPath}homer-16.webp` },
  { id: "homer-17", image: `${homerPath}homer-17.webp` },
  { id: "homer-18", image: `${homerPath}homer-18.webp` },
  { id: "homer-19", image: `${homerPath}homer-19.webp` },
  { id: "homer-20", image: `${homerPath}homer-20.webp` },
  { id: "homer-21", image: `${homerPath}homer-21.webp` },
  { id: "homer-22", image: `${homerPath}homer-22.webp` },
  { id: "homer-23", image: `${homerPath}homer-23.webp` },
  { id: "homer-24", image: `${homerPath}homer-24.webp` },
  { id: "homer-25", image: `${homerPath}homer-25.webp` },
  { id: "homer-26", image: `${homerPath}homer-26.webp` },
  { id: "homer-27", image: `${homerPath}homer-27.webp` },
  { id: "homer-28", image: `${homerPath}homer-28.webp` },
  { id: "homer-29", image: `${homerPath}homer-29.webp` },
  { id: "homer-30", image: `${homerPath}homer-30.webp` },
  { id: "homer-31", image: `${homerPath}homer-31.webp` },
  { id: "homer-32", image: `${homerPath}homer-32.webp` },
  { id: "homer-33", image: `${homerPath}homer-33.webp` },
  { id: "homer-34", image: `${homerPath}homer-34.webp` },
  { id: "homer-35", image: `${homerPath}homer-35.webp` },
  { id: "homer-36", image: `${homerPath}homer-36.webp` },
  { id: "homer-37", image: `${homerPath}homer-37.webp` },
  { id: "homer-38", image: `${homerPath}homer-38.webp` },
  { id: "homer-39", image: `${homerPath}homer-39.webp` },
  { id: "homer-40", image: `${homerPath}homer-40.webp` },
]

const hotEatPath = "/stickers/hot-eat/"
const HOT_EAT = [
  { id: "hot-eat-1", image: `${hotEatPath}hot-eat-1.webp` },
  { id: "hot-eat-2", image: `${hotEatPath}hot-eat-2.webp` },
  { id: "hot-eat-3", image: `${hotEatPath}hot-eat-3.webp` },
  { id: "hot-eat-4", image: `${hotEatPath}hot-eat-4.webp` },
  { id: "hot-eat-5", image: `${hotEatPath}hot-eat-5.webp` },
  { id: "hot-eat-6", image: `${hotEatPath}hot-eat-6.webp` },
  { id: "hot-eat-7", image: `${hotEatPath}hot-eat-7.webp` },
  { id: "hot-eat-8", image: `${hotEatPath}hot-eat-8.webp` },
  { id: "hot-eat-9", image: `${hotEatPath}hot-eat-9.webp` },
  { id: "hot-eat-10", image: `${hotEatPath}hot-eat-10.webp` },
  { id: "hot-eat-11", image: `${hotEatPath}hot-eat-11.webp` },
  { id: "hot-eat-12", image: `${hotEatPath}hot-eat-12.webp` },
  { id: "hot-eat-13", image: `${hotEatPath}hot-eat-13.webp` },
  { id: "hot-eat-14", image: `${hotEatPath}hot-eat-14.webp` },
  { id: "hot-eat-15", image: `${hotEatPath}hot-eat-15.webp` },
  { id: "hot-eat-16", image: `${hotEatPath}hot-eat-16.webp` },
  { id: "hot-eat-17", image: `${hotEatPath}hot-eat-17.webp` },
  { id: "hot-eat-18", image: `${hotEatPath}hot-eat-18.webp` },
  { id: "hot-eat-19", image: `${hotEatPath}hot-eat-19.webp` },
  { id: "hot-eat-20", image: `${hotEatPath}hot-eat-20.webp` },
  { id: "hot-eat-21", image: `${hotEatPath}hot-eat-21.webp` },
  { id: "hot-eat-22", image: `${hotEatPath}hot-eat-22.webp` },
  { id: "hot-eat-23", image: `${hotEatPath}hot-eat-23.webp` },
  { id: "hot-eat-24", image: `${hotEatPath}hot-eat-24.webp` },
  { id: "hot-eat-25", image: `${hotEatPath}hot-eat-25.webp` },
  { id: "hot-eat-26", image: `${hotEatPath}hot-eat-26.webp` },
  { id: "hot-eat-27", image: `${hotEatPath}hot-eat-27.webp` },
  { id: "hot-eat-28", image: `${hotEatPath}hot-eat-28.webp` },
  { id: "hot-eat-29", image: `${hotEatPath}hot-eat-29.webp` },
  { id: "hot-eat-30", image: `${hotEatPath}hot-eat-30.webp` },
  { id: "hot-eat-31", image: `${hotEatPath}hot-eat-31.webp` },
  { id: "hot-eat-32", image: `${hotEatPath}hot-eat-32.webp` },
  { id: "hot-eat-33", image: `${hotEatPath}hot-eat-33.webp` },
  { id: "hot-eat-34", image: `${hotEatPath}hot-eat-34.webp` },
  { id: "hot-eat-35", image: `${hotEatPath}hot-eat-35.webp` },
  { id: "hot-eat-36", image: `${hotEatPath}hot-eat-36.webp` },
  { id: "hot-eat-37", image: `${hotEatPath}hot-eat-37.webp` },
  { id: "hot-eat-38", image: `${hotEatPath}hot-eat-38.webp` },
  { id: "hot-eat-39", image: `${hotEatPath}hot-eat-39.webp` },
  { id: "hot-eat-40", image: `${hotEatPath}hot-eat-40.webp` },
]

const karlsonPath = "/stickers/karlson/"
const CARLSON = [
  { id: "karlson-1", image: `${karlsonPath}karlson-1.webp` },
  { id: "karlson-2", image: `${karlsonPath}karlson-2.webp` },
  { id: "karlson-3", image: `${karlsonPath}karlson-3.webp` },
  { id: "karlson-4", image: `${karlsonPath}karlson-4.webp` },
  { id: "karlson-5", image: `${karlsonPath}karlson-5.webp` },
  { id: "karlson-6", image: `${karlsonPath}karlson-6.webp` },
  { id: "karlson-7", image: `${karlsonPath}karlson-7.webp` },
  { id: "karlson-8", image: `${karlsonPath}karlson-8.webp` },
  { id: "karlson-9", image: `${karlsonPath}karlson-9.webp` },
  { id: "karlson-10", image: `${karlsonPath}karlson-10.webp` },
  { id: "karlson-11", image: `${karlsonPath}karlson-11.webp` },
  { id: "karlson-12", image: `${karlsonPath}karlson-12.webp` },
  { id: "karlson-13", image: `${karlsonPath}karlson-13.webp` },
  { id: "karlson-14", image: `${karlsonPath}karlson-14.webp` },
  { id: "karlson-15", image: `${karlsonPath}karlson-15.webp` },
  { id: "karlson-16", image: `${karlsonPath}karlson-16.webp` },
  { id: "karlson-17", image: `${karlsonPath}karlson-17.webp` },
  { id: "karlson-18", image: `${karlsonPath}karlson-18.webp` },
  { id: "karlson-19", image: `${karlsonPath}karlson-19.webp` },
  { id: "karlson-20", image: `${karlsonPath}karlson-20.webp` },
  { id: "karlson-21", image: `${karlsonPath}karlson-21.webp` },
  { id: "karlson-22", image: `${karlsonPath}karlson-22.webp` },
  { id: "karlson-23", image: `${karlsonPath}karlson-23.webp` },
  { id: "karlson-24", image: `${karlsonPath}karlson-24.webp` },
  { id: "karlson-25", image: `${karlsonPath}karlson-25.webp` },
]

const memsTwoPath = "/stickers/mems-two/"
const MEMS_TWO = [
  { id: "mems-two-1", image: `${memsTwoPath}mems-two-1.webp` },
  { id: "mems-two-2", image: `${memsTwoPath}mems-two-2.webp` },
  { id: "mems-two-3", image: `${memsTwoPath}mems-two-3.webp` },
  { id: "mems-two-4", image: `${memsTwoPath}mems-two-4.webp` },
  { id: "mems-two-5", image: `${memsTwoPath}mems-two-5.webp` },
  { id: "mems-two-6", image: `${memsTwoPath}mems-two-6.webp` },
  { id: "mems-two-7", image: `${memsTwoPath}mems-two-7.webp` },
  { id: "mems-two-8", image: `${memsTwoPath}mems-two-8.webp` },
  { id: "mems-two-9", image: `${memsTwoPath}mems-two-9.webp` },
  { id: "mems-two-10", image: `${memsTwoPath}mems-two-10.webp` },
  { id: "mems-two-11", image: `${memsTwoPath}mems-two-11.webp` },
  { id: "mems-two-12", image: `${memsTwoPath}mems-two-12.webp` },
  { id: "mems-two-13", image: `${memsTwoPath}mems-two-13.webp` },
  { id: "mems-two-14", image: `${memsTwoPath}mems-two-14.webp` },
  { id: "mems-two-15", image: `${memsTwoPath}mems-two-15.webp` },
  { id: "mems-two-16", image: `${memsTwoPath}mems-two-16.webp` },
  { id: "mems-two-17", image: `${memsTwoPath}mems-two-17.webp` },
  { id: "mems-two-18", image: `${memsTwoPath}mems-two-18.webp` },
  { id: "mems-two-19", image: `${memsTwoPath}mems-two-19.webp` },
  { id: "mems-two-20", image: `${memsTwoPath}mems-two-20.webp` },
  { id: "mems-two-21", image: `${memsTwoPath}mems-two-21.webp` },
  { id: "mems-two-22", image: `${memsTwoPath}mems-two-22.webp` },
  { id: "mems-two-23", image: `${memsTwoPath}mems-two-23.webp` },
  { id: "mems-two-24", image: `${memsTwoPath}mems-two-24.webp` },
  { id: "mems-two-25", image: `${memsTwoPath}mems-two-25.webp` },
  { id: "mems-two-26", image: `${memsTwoPath}mems-two-26.webp` },
  { id: "mems-two-27", image: `${memsTwoPath}mems-two-27.webp` },
  { id: "mems-two-28", image: `${memsTwoPath}mems-two-28.webp` },
  { id: "mems-two-29", image: `${memsTwoPath}mems-two-29.webp` },
  { id: "mems-two-30", image: `${memsTwoPath}mems-two-30.webp` },
  { id: "mems-two-31", image: `${memsTwoPath}mems-two-31.webp` },
  { id: "mems-two-32", image: `${memsTwoPath}mems-two-32.webp` },
  { id: "mems-two-33", image: `${memsTwoPath}mems-two-33.webp` },
  { id: "mems-two-34", image: `${memsTwoPath}mems-two-34.webp` },
  { id: "mems-two-35", image: `${memsTwoPath}mems-two-35.webp` },
  { id: "mems-two-36", image: `${memsTwoPath}mems-two-36.webp` },
  { id: "mems-two-37", image: `${memsTwoPath}mems-two-37.webp` },
  { id: "mems-two-38", image: `${memsTwoPath}mems-two-38.webp` },
  { id: "mems-two-39", image: `${memsTwoPath}mems-two-39.webp` },
  { id: "mems-two-40", image: `${memsTwoPath}mems-two-40.webp` },
  { id: "mems-two-41", image: `${memsTwoPath}mems-two-41.webp` },
  { id: "mems-two-42", image: `${memsTwoPath}mems-two-42.webp` },
  { id: "mems-two-43", image: `${memsTwoPath}mems-two-43.webp` },
  { id: "mems-two-44", image: `${memsTwoPath}mems-two-44.webp` },
  { id: "mems-two-45", image: `${memsTwoPath}mems-two-45.webp` },
  { id: "mems-two-46", image: `${memsTwoPath}mems-two-46.webp` },
  { id: "mems-two-47", image: `${memsTwoPath}mems-two-47.webp` },
  { id: "mems-two-48", image: `${memsTwoPath}mems-two-48.webp` },
  { id: "mems-two-49", image: `${memsTwoPath}mems-two-49.webp` },
  { id: "mems-two-50", image: `${memsTwoPath}mems-two-50.webp` },
  { id: "mems-two-51", image: `${memsTwoPath}mems-two-51.webp` },
  { id: "mems-two-52", image: `${memsTwoPath}mems-two-52.webp` },
  { id: "mems-two-53", image: `${memsTwoPath}mems-two-53.webp` },
  { id: "mems-two-54", image: `${memsTwoPath}mems-two-54.webp` },
  { id: "mems-two-55", image: `${memsTwoPath}mems-two-55.webp` },
  { id: "mems-two-56", image: `${memsTwoPath}mems-two-56.webp` },
  { id: "mems-two-57", image: `${memsTwoPath}mems-two-57.webp` },
  { id: "mems-two-58", image: `${memsTwoPath}mems-two-58.webp` },
  { id: "mems-two-59", image: `${memsTwoPath}mems-two-59.webp` },
  { id: "mems-two-60", image: `${memsTwoPath}mems-two-60.webp` },
  { id: "mems-two-61", image: `${memsTwoPath}mems-two-61.webp` },
  { id: "mems-two-62", image: `${memsTwoPath}mems-two-62.webp` },
  { id: "mems-two-63", image: `${memsTwoPath}mems-two-63.webp` },
  { id: "mems-two-64", image: `${memsTwoPath}mems-two-64.webp` },
  { id: "mems-two-65", image: `${memsTwoPath}mems-two-65.webp` },
  { id: "mems-two-66", image: `${memsTwoPath}mems-two-66.webp` },
  { id: "mems-two-67", image: `${memsTwoPath}mems-two-67.webp` },
  { id: "mems-two-68", image: `${memsTwoPath}mems-two-68.webp` },
  { id: "mems-two-69", image: `${memsTwoPath}mems-two-69.webp` },
  { id: "mems-two-70", image: `${memsTwoPath}mems-two-70.webp` },
  { id: "mems-two-71", image: `${memsTwoPath}mems-two-71.webp` },
  { id: "mems-two-72", image: `${memsTwoPath}mems-two-72.webp` },
  { id: "mems-two-73", image: `${memsTwoPath}mems-two-73.webp` },
  { id: "mems-two-74", image: `${memsTwoPath}mems-two-74.webp` },
  { id: "mems-two-75", image: `${memsTwoPath}mems-two-75.webp` },
  { id: "mems-two-76", image: `${memsTwoPath}mems-two-76.webp` },
  { id: "mems-two-77", image: `${memsTwoPath}mems-two-77.webp` },
  { id: "mems-two-78", image: `${memsTwoPath}mems-two-78.webp` },
  { id: "mems-two-79", image: `${memsTwoPath}mems-two-79.webp` },
  { id: "mems-two-80", image: `${memsTwoPath}mems-two-80.webp` },
  { id: "mems-two-81", image: `${memsTwoPath}mems-two-81.webp` },
  { id: "mems-two-82", image: `${memsTwoPath}mems-two-82.webp` },
  { id: "mems-two-83", image: `${memsTwoPath}mems-two-83.webp` },
  { id: "mems-two-84", image: `${memsTwoPath}mems-two-84.webp` },
  { id: "mems-two-85", image: `${memsTwoPath}mems-two-85.webp` },
  { id: "mems-two-86", image: `${memsTwoPath}mems-two-86.webp` },
  { id: "mems-two-87", image: `${memsTwoPath}mems-two-87.webp` },
  { id: "mems-two-88", image: `${memsTwoPath}mems-two-88.webp` },
  { id: "mems-two-89", image: `${memsTwoPath}mems-two-89.webp` },
  { id: "mems-two-90", image: `${memsTwoPath}mems-two-90.webp` },
  { id: "mems-two-91", image: `${memsTwoPath}mems-two-91.webp` },
  { id: "mems-two-92", image: `${memsTwoPath}mems-two-92.webp` },
  { id: "mems-two-93", image: `${memsTwoPath}mems-two-93.webp` },
  { id: "mems-two-94", image: `${memsTwoPath}mems-two-94.webp` },
]

const gingerbreadPath = "/stickers/gingerbread/"
const GINGERBREAD = [
  { id: "gingerbread-1", image: `${gingerbreadPath}gingerbread-1.webp` },
  { id: "gingerbread-2", image: `${gingerbreadPath}gingerbread-2.webp` },
  { id: "gingerbread-3", image: `${gingerbreadPath}gingerbread-3.webp` },
  { id: "gingerbread-4", image: `${gingerbreadPath}gingerbread-4.webp` },
  { id: "gingerbread-5", image: `${gingerbreadPath}gingerbread-5.webp` },
  { id: "gingerbread-6", image: `${gingerbreadPath}gingerbread-6.webp` },
  { id: "gingerbread-7", image: `${gingerbreadPath}gingerbread-7.webp` },
  { id: "gingerbread-8", image: `${gingerbreadPath}gingerbread-8.webp` },
  { id: "gingerbread-9", image: `${gingerbreadPath}gingerbread-9.webp` },
  { id: "gingerbread-10", image: `${gingerbreadPath}gingerbread-10.webp` },
  { id: "gingerbread-11", image: `${gingerbreadPath}gingerbread-11.webp` },
  { id: "gingerbread-12", image: `${gingerbreadPath}gingerbread-12.webp` },
  { id: "gingerbread-13", image: `${gingerbreadPath}gingerbread-13.webp` },
  { id: "gingerbread-14", image: `${gingerbreadPath}gingerbread-14.webp` },
  { id: "gingerbread-15", image: `${gingerbreadPath}gingerbread-15.webp` },
  { id: "gingerbread-16", image: `${gingerbreadPath}gingerbread-16.webp` },
  { id: "gingerbread-17", image: `${gingerbreadPath}gingerbread-17.webp` },
  { id: "gingerbread-18", image: `${gingerbreadPath}gingerbread-18.webp` },
  { id: "gingerbread-19", image: `${gingerbreadPath}gingerbread-19.webp` },
  { id: "gingerbread-20", image: `${gingerbreadPath}gingerbread-20.webp` },
  { id: "gingerbread-21", image: `${gingerbreadPath}gingerbread-21.webp` },
  { id: "gingerbread-22", image: `${gingerbreadPath}gingerbread-22.webp` },
  { id: "gingerbread-23", image: `${gingerbreadPath}gingerbread-23.webp` },
  { id: "gingerbread-24", image: `${gingerbreadPath}gingerbread-24.webp` },
  { id: "gingerbread-25", image: `${gingerbreadPath}gingerbread-25.webp` },
  { id: "gingerbread-26", image: `${gingerbreadPath}gingerbread-26.webp` },
  { id: "gingerbread-27", image: `${gingerbreadPath}gingerbread-27.webp` },
  { id: "gingerbread-28", image: `${gingerbreadPath}gingerbread-28.webp` },
]

const nifflerPath = "/stickers/niffler/"
const NIFFLER = [
  { id: "niffler-1", image: `${nifflerPath}niffler-1.webp` },
  { id: "niffler-2", image: `${nifflerPath}niffler-2.webp` },
  { id: "niffler-3", image: `${nifflerPath}niffler-3.webp` },
  { id: "niffler-4", image: `${nifflerPath}niffler-4.webp` },
  { id: "niffler-5", image: `${nifflerPath}niffler-5.webp` },
  { id: "niffler-6", image: `${nifflerPath}niffler-6.webp` },
  { id: "niffler-7", image: `${nifflerPath}niffler-7.webp` },
  { id: "niffler-8", image: `${nifflerPath}niffler-8.webp` },
  { id: "niffler-9", image: `${nifflerPath}niffler-9.webp` },
  { id: "niffler-10", image: `${nifflerPath}niffler-10.webp` },
  { id: "niffler-11", image: `${nifflerPath}niffler-11.webp` },
  { id: "niffler-12", image: `${nifflerPath}niffler-12.webp` },
  { id: "niffler-13", image: `${nifflerPath}niffler-13.webp` },
  { id: "niffler-14", image: `${nifflerPath}niffler-14.webp` },
  { id: "niffler-15", image: `${nifflerPath}niffler-15.webp` },
  { id: "niffler-16", image: `${nifflerPath}niffler-16.webp` },
  { id: "niffler-17", image: `${nifflerPath}niffler-17.webp` },
  { id: "niffler-18", image: `${nifflerPath}niffler-18.webp` },
  { id: "niffler-19", image: `${nifflerPath}niffler-19.webp` },
  { id: "niffler-20", image: `${nifflerPath}niffler-20.webp` },
  { id: "niffler-21", image: `${nifflerPath}niffler-21.webp` },
  { id: "niffler-22", image: `${nifflerPath}niffler-22.webp` },
  { id: "niffler-23", image: `${nifflerPath}niffler-23.webp` },
  { id: "niffler-24", image: `${nifflerPath}niffler-24.webp` },
]
const wolfPath = "/stickers/wolf/"
const WOLF = [
  { id: "wolf-1", image: `${wolfPath}wolf-1.webp` },
  { id: "wolf-2", image: `${wolfPath}wolf-2.webp` },
  { id: "wolf-3", image: `${wolfPath}wolf-3.webp` },
  { id: "wolf-4", image: `${wolfPath}wolf-4.webp` },
  { id: "wolf-5", image: `${wolfPath}wolf-5.webp` },
  { id: "wolf-6", image: `${wolfPath}wolf-6.webp` },
  { id: "wolf-7", image: `${wolfPath}wolf-7.webp` },
  { id: "wolf-8", image: `${wolfPath}wolf-8.webp` },
  { id: "wolf-9", image: `${wolfPath}wolf-9.webp` },
  { id: "wolf-10", image: `${wolfPath}wolf-10.webp` },
  { id: "wolf-11", image: `${wolfPath}wolf-11.webp` },
  { id: "wolf-12", image: `${wolfPath}wolf-12.webp` },
  { id: "wolf-13", image: `${wolfPath}wolf-13.webp` },
  { id: "wolf-14", image: `${wolfPath}wolf-14.webp` },
  { id: "wolf-15", image: `${wolfPath}wolf-15.webp` },
  { id: "wolf-16", image: `${wolfPath}wolf-16.webp` },
  { id: "wolf-17", image: `${wolfPath}wolf-17.webp` },
  { id: "wolf-18", image: `${wolfPath}wolf-18.webp` },
  { id: "wolf-19", image: `${wolfPath}wolf-19.webp` },
  { id: "wolf-20", image: `${wolfPath}wolf-20.webp` },
  { id: "wolf-21", image: `${wolfPath}wolf-21.webp` },
  { id: "wolf-22", image: `${wolfPath}wolf-22.webp` },
  { id: "wolf-23", image: `${wolfPath}wolf-23.webp` },
  { id: "wolf-24", image: `${wolfPath}wolf-24.webp` },
  { id: "wolf-25", image: `${wolfPath}wolf-25.webp` },
  { id: "wolf-26", image: `${wolfPath}wolf-26.webp` },
  { id: "wolf-27", image: `${wolfPath}wolf-27.webp` },
  { id: "wolf-28", image: `${wolfPath}wolf-28.webp` },
  { id: "wolf-29", image: `${wolfPath}wolf-29.webp` },
  { id: "wolf-30", image: `${wolfPath}wolf-30.webp` },
  { id: "wolf-31", image: `${wolfPath}wolf-31.webp` },
  { id: "wolf-32", image: `${wolfPath}wolf-32.webp` },
  { id: "wolf-33", image: `${wolfPath}wolf-33.webp` },
  { id: "wolf-34", image: `${wolfPath}wolf-34.webp` },
  { id: "wolf-35", image: `${wolfPath}wolf-35.webp` },
  { id: "wolf-36", image: `${wolfPath}wolf-36.webp` },
  { id: "wolf-37", image: `${wolfPath}wolf-37.webp` },
  { id: "wolf-38", image: `${wolfPath}wolf-38.webp` },
  { id: "wolf-39", image: `${wolfPath}wolf-39.webp` },
  { id: "wolf-40", image: `${wolfPath}wolf-40.webp` },
  { id: "wolf-41", image: `${wolfPath}wolf-41.webp` },
  { id: "wolf-42", image: `${wolfPath}wolf-42.webp` },
  { id: "wolf-43", image: `${wolfPath}wolf-43.webp` },
]

const slimePath = "/stickers/slime/"
const SLIME = [
  { id: "slime-1", image: `${slimePath}slime-1.png` },
  { id: "slime-2", image: `${slimePath}slime-2.png` },
  { id: "slime-3", image: `${slimePath}slime-3.png` },
  { id: "slime-4", image: `${slimePath}slime-4.png` },
  { id: "slime-5", image: `${slimePath}slime-5.png` },
  { id: "slime-6", image: `${slimePath}slime-6.png` },
  { id: "slime-7", image: `${slimePath}slime-7.png` },
  { id: "slime-8", image: `${slimePath}slime-8.png` },
  { id: "slime-9", image: `${slimePath}slime-9.png` },
  { id: "slime-10", image: `${slimePath}slime-10.png` },
  { id: "slime-11", image: `${slimePath}slime-11.png` },
  { id: "slime-12", image: `${slimePath}slime-12.png` },
  { id: "slime-13", image: `${slimePath}slime-13.png` },
  { id: "slime-14", image: `${slimePath}slime-14.png` },
  { id: "slime-15", image: `${slimePath}slime-15.png` },
  { id: "slime-16", image: `${slimePath}slime-16.png` },
  { id: "slime-17", image: `${slimePath}slime-17.png` },
  { id: "slime-18", image: `${slimePath}slime-18.png` },
  { id: "slime-19", image: `${slimePath}slime-19.png` },
  { id: "slime-20", image: `${slimePath}slime-20.png` },
  { id: "slime-21", image: `${slimePath}slime-21.png` },
  { id: "slime-22", image: `${slimePath}slime-22.png` },
  { id: "slime-23", image: `${slimePath}slime-23.png` },
  { id: "slime-24", image: `${slimePath}slime-24.png` },
  { id: "slime-25", image: `${slimePath}slime-25.png` },
  { id: "slime-26", image: `${slimePath}slime-26.png` },
  { id: "slime-27", image: `${slimePath}slime-27.png` },
  { id: "slime-28", image: `${slimePath}slime-28.png` },
  { id: "slime-29", image: `${slimePath}slime-29.png` },
  { id: "slime-30", image: `${slimePath}slime-30.png` },
  { id: "slime-31", image: `${slimePath}slime-31.png` },
  { id: "slime-32", image: `${slimePath}slime-32.png` },
  { id: "slime-33", image: `${slimePath}slime-33.png` },
  { id: "slime-34", image: `${slimePath}slime-34.png` },
  { id: "slime-35", image: `${slimePath}slime-35.png` },
  { id: "slime-36", image: `${slimePath}slime-36.png` },
  { id: "slime-37", image: `${slimePath}slime-37.png` },
  { id: "slime-38", image: `${slimePath}slime-38.png` },
  { id: "slime-39", image: `${slimePath}slime-39.png` },
  { id: "slime-40", image: `${slimePath}slime-40.png` },
  { id: "slime-41", image: `${slimePath}slime-41.png` },
  { id: "slime-42", image: `${slimePath}slime-42.png` },
  { id: "slime-43", image: `${slimePath}slime-43.png` },
  { id: "slime-44", image: `${slimePath}slime-44.png` },
  { id: "slime-45", image: `${slimePath}slime-45.png` },
  { id: "slime-46", image: `${slimePath}slime-46.png` },
  { id: "slime-47", image: `${slimePath}slime-47.png` },
  { id: "slime-48", image: `${slimePath}slime-48.png` },
]

export type StickersTypeItem = { id: string; image: string }

type StickersType = Record<string, StickersTypeItem[]>

export const STICKERS: StickersType = {
  mems: MEMS,
  capybara: CAPYBARA,
  bender: BENDER,
  cheshire: CHESHIRE,
  cthulhu: CTHULHU,
  slime: SLIME,
  gingerbread: GINGERBREAD,
  niffler: NIFFLER,
  wolf: WOLF,
  gucci: GUCCI,
  homer: HOMER,
  carlson: CARLSON,
  memsTwo: MEMS_TWO,
  hotEat: HOT_EAT,
}
