import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import "@/styles/reset.scss"
// import Header from "@/components/header/Header"
// import Navbar from "@/components/navbar/Navbar"
// import Footer from "@/components/footer/Footer"

// import ReduxProvider from "@/providers/ReduxProvider"
import NotificationProvider from "@/providers/NotificationProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Like Social",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "LikeSocial",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="LikeSocial" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NotificationProvider>{children}</NotificationProvider>
        {/* <ReduxProvider>{children}</ReduxProvider> */}
      </body>
    </html>
  )
}

// Назначение	Цвет	HEX
// Фон	Светло-сиреневый	#F3E8FF
// Основной	Твой фиолет	#6400B9
// Вторичный	Нежно-фиолетовый	#A366FF
// Акценты	Лимонно-жёлтый	#FFD700
// Текст	Тёмно-серый	#1E1E1E
